development:
  adapter: async
  # adapter: redis
  # url: localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: budgetmanagement_production
